### ISSUE TITLE
more general types

### ISSUE THREAD

**Issue by garykl** [ixmatus/orgmode-parse#15]
Wouldn't it be nicer to put the types into the module Data.Orgmode instead of Data.Orgmode.Parse? Nonparsing actions should be handled with the help of those types, like searching and filtering.

(By the way, are those types used anywhere else already?)

**Comment by ixmatus** [comment]
I do not disagree, Real Life has been in the way for quite some time so
this library hasn't had the amount of love from me that it should. I'm very
open to pull requests if there's anything you want to fix or improve upon :)

On Fri, Jan 8, 2016 at 12:45 PM, Spiehr <notifications@github.com> wrote:

> Wouldn't it be nicer to put the types into the module DataOrgmode instead
> of DataOrgmodeParse? Nonparsing actions should be handled with the help of
> those types, like searching and filtering
>
> (By the way, are those types used anywhere else already?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmentat/orgmode-parse/issues/15>.
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>
