### ISSUE TITLE
Library version 0.3 Hackage approval?

### ISSUE THREAD

**Issue by jakeisnt** [ixmatus/orgmode-parse#56]
On Hackage, the package recommends using 0.23 over 0.3 and doesn't provide a build for 0.3 on NixOS. Why is this?

**Comment by ixmatus** [comment]
@jakeisnt probably because 0.3 is not recommended? I do not recommend 0.3 because some work that was merged into that release badly broke the parser (#49) and I haven't got around to fixing it. I'm still a little confused about what you need so let me know how else I can help.
