### ISSUE TITLE
Skip more spaces around syntactic terms

### ISSUE THREAD

**Issue by nushio3** [ixmatus/orgmode-parse#8]
Hi,

This is a tricky issue when we design a parser --- to parse off allowed spaces. Today I stumbled upon this issue when I tried to parse "  SCHEDULED: <...>" line with preceding spaces.

Here is a quick workaround for me: https://github.com/digitalmentat/orgmode-parse/compare/master...nushio3:issue-spaces but surely, this is too ad-hoc.

Parnell, do you have any preferred style for this? Should every syntactic terms absorb spaces before them, after them, or both?

Upon decision, we can identify where `skipSpace` is missing and insert them systematically.

Optionally, we can introduce some token parser combinator that creates a space-absorbing parsers, like `token` from https://hackage.haskell.org/package/parsers-0.12.1.1/docs/Text-Parser-Token.html#v:token .

**Comment by ixmatus** [comment]
I think skipSpace is not too ad-hoc, actually, and tends to follow idiomatic attoparsec use (note the existence of `skipSpace` is even its own function!)

However, I do like the focus on generalizing more - my intuition is telling me that we should tackle this sometime soon but not yet.

**Comment by nushio3** [comment]
The particular problem is fixed by #11 , but I'll leave this issue as it is to remember "that we should tackle this sometime soon." Please don't hesitate to close it if you think it became appropriate to do so.

**Comment by ixmatus** [comment]
Closing this as it's quite old and I think the accepted solution works just fine.
